<?php
/**
 * @file
 * Contains dcamp_landing.module
 */

/**
 * Implements hook_theme.
 */
function dcamp_landing_theme($existing, $type, $theme, $path){
 return [
   'landing' => array(
     'render element' => 'elements',
   ),
 ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dcamp_landing_theme_suggestions_landing(array $variables){
  $suggestions = array();
  $suggestions[] = 'landing__'. $variables['elements']['#id'];
  return $suggestions;
}


/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Create Theme suggestions for the page.html.twig depending on the landing
 * page.
 * @param array $suggestions
 * @param array $variables
 */
function dcamp_landing_theme_suggestions_page_alter(array &$suggestions, array $variables){
  /**
   * @var \Symfony\Component\HttpFoundation\Request $request
   */
  $request = \Drupal::request();
  $config = $request->attributes->get('config');
  if($config && is_a($config, 'Drupal\dcamp_landing\Entity\DcampLanding')){
    $suggestions[] = 'page__landing';
  }
}

/**
 * Prepares variables for landing templates.
 */
function template_preprocess_landing(&$variables){
  $variables['blocks'] = $variables['elements']['#blocks'];
  $variables['id'] = $variables['elements']['#id'];
}