dcamp_landing.dcamp_landing.*:
  type: config_entity
  label: 'DrupalCamp Landing config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    path:
      type: string
    blocks:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          weight:
            type: integer